[[relativistic_velocities_section]]
=== Dynamic Features at Relativistic Velocities

Newtonian physics, the physics of everyday life, served us well for almost 200 years. By the late 1800's, however, it became clear that something more was needed. 

==== The birth of relativity

Since light behaves like a wave, there must be a material for the waves to propagate through. Physicists called this material the luminiferous aether. The aether was an undetectable substance which permiates space. It provided a universal reference frame against which absolute motion could be measured.

According to this theory, a measurement of the speed of light would vary depending on the motion of the measuring apparatus through the universal reference frame, the aether. The speed of light through the aether would be a fixed value. Measurements of the speed of light would be the sum of the velocity of the measurement appraratus relative to the aether and the speed of light through aether.

Consider a measuring apparatus which consists of a light separated a fixed distance from a detector. If the apparatus is oriented in the same direction as the motion of the apparatus through the aether, then the measured speed of light would be higher. If the apparatus was traveling in the opposit direction, then the measured speed of light would be lower.    

should be higher for an object moving toward a light source and lower for one moving away.

In 1887, Michaelson and Morley built such an apparatus. Their experiments showed that the speed of light was the same no matter how their apparatus was oriented. The inescapable conclusion was that there is no luminiferous aether. That there is no universal reference system. There is no abolute motion. All motion must be a measurement of relative motion between two objects.

==== Lorentz Transformation

The Lorentz transformations were the result of attempts by Lorentz and others to explain how the speed of light could be independent of the underlying reference frame without discarding the luminiferous aether. While the aether theory is long discarded, Lorentz Transforms are consistent with Special Relativity which makes them still useful today.

Consider a reference frame 'A' which is moving in respect to an observer at 'B'. Lorentz asserts that 'A' and 'B' measure reality using two different reference frames. Transformation from reference frame 'A' (Fa) to Reference Frame 'B' (Fb) requires a transformation that accounts for the effect of velocity. Central to this transformation is the The Lorentz factor (g) which is defined as:

 g = 1 / (sqrt(1 - (v^2 / c^2)))
 
In each reference frame, an observer can use a local coordinate system (usually Cartesian coordinates in this context) to measure lengths, and a clock to measure time intervals. An event is something that happens at a point in space at an instant of time, or more formally a point in spacetime. The transformations connect the space and time coordinates of an event as measured by an observer in each frame. 

In the reference frame "F" which is stationary, the coordinate defined are x, y, z, and t.  In another reference frame F' which moves at a velocity v which is relative to F and the observer defines coordinate in the moving reverence frame as x', y', z', t'. In both the reference frames the coordinate axis are parallel and they remain mutually perpedicular.  The relative motion is along the xx' axes. At t = t' = 0, the origins in both reference frames are the same (x,y,z) = (x',y',z') = (0,0,0).

x' = g(x-vt)
t' = g(t-(vx/c^2))
y' = y
z' = z

Show how a velocity of 1/2 c will generate space and time contraction.

This is not a complete coordinate transformation since F' has to be rotated and translated so as to be co-linear with F. However, it does add the impact that relative velocity (v) has on the measurements of x and t. In most cases this impact is neglegible (v^2 / c^2 approaches 0).  However, when v is a significant percentage of c it should be applied.

==== Minkowski Space Time



It is basically a combination of 3-dimensional Euclidean Space and time into a 4-dimensional manifold, where the interval of spacetime that exists between any two events is not dependent on the inertial frame of reference. 

Minkowski spacetime is a 4-dimensional coordinate system in which the axes are given by (x, y, z, ct)

Where ct is time (t) times the speed of light (c)

ds^2 = -c^2 dt^2 + dx^2 + dy^2, + dz^2 = the differential arc length in space time where:

. dt = change in time
. dx = change in x direction
. dy = change in y direction
. dz = change in z direction

Key point - while a Lorentz transformation deals with spatial measurements, Minkowski space includes time as part of that space-time.  Thus ds is an arc length through space-time as opposed to a difference in x as in the Lorentz transform.

Question, since c^2dt^2 is a negative term, does that inply that ct is an imaginary number orthagonal to x, y, and z (cti) such that i^2 = -1?

Yes for complex Minkowski space time. Here it is expressed as x^2 + y^2 + z^2 + (ict)^2 = const.

Complex Minkowski spacetime was replaced with real Minkowski space time where time is a real coordinate rather than an imaginary one.

Where v is velocity, and x, y, and z are Cartesian coordinates in 3-dimensional space, and c is the constant representing the universal speed limit, and t is time, the four-dimensional vector v = (ct, x, y, z) = (ct, **r**) is classified according to the sign of (c^2 t^2) − r^2. A vector is **timelike** if (c^2 t^2) > r^2, **spacelike** if (c^2 t^2) < r^2, and **null** or **lightlike** if (c^2 t^2) = r^2. This can be expressed in terms of the sign of η(v, v) as well, which depends on the signature. The classification of any vector will be the same in all frames of reference that are related by a Lorentz transformation (but not by a general Poincaré transformation because the origin may then be displaced) because of the invariance of the interval.


==== Musings

A Minkowski coordinate reference system is M4D.

Minkowski spacetime has no natural CRS. All M4D CRS are local.

M4D is a spatial CRS. the axis are x, y, z, and ct. 

Note the units of ct -> M/S * S = M -> all axis of a M4D CRS have the same units of measure.

Consider an Observer O and an Observed phenomenon O'.

Discuss Worlds and world lines

If O' is stationary in respect to O, then Newtonian physics applies. 

If O' is moving in respect to O, then it has a world line as shown in figure ---

Notice that the M4D CRS of O' is inclined in respect to the CRS of O. It has undergone a rotation. The effect of this rotation is a contraction in both the measured X and ct coordinates. The ammount of contraction depends on the rotation of M4D O' in respect to M4D O. 

So M4D O' and M4D O can be evaluated in terms of our standard concepts of translation and rotation.

The actual mathematics involved can be packaged in a reusable library, similar to the way terrestrial CRS conversions are handled by GeoTRANS. It is sufficient for geospatial users to understand the required parameters and the basic principles of the transforms.

Also - this requires that the general practice of measuring across coordinate reference systems be matured. CRS and CRS transformation will play a much larger role in spatial-temporal data processing than it has in the past.




