=== Temporal Properties

Proposition: Features can change in state as well at location

ISO 19141 introduced the concept of a One Parameter Geometry.  

MF_OneParamGeometry: 

A one parameter set of geometries is a function f from an interval t Î [a, b] such that f(t) is a geometry and for each point P Î f(a) there is a one parameter set of points (called the trajectory of P) P(t) : [a, b] ® P(t) such that P(t) Î f(t). A leaf of a one parameter set of geometries is the geometry f(t) at a particular value of the parameter. The set of geometries forms a prism that is the set of points in the union of the geometries (or the union of the trajectories).  

The type "MF_OneParamGeometry" acts as the root classifier for all geometric object classified as one parameter sets of geometric objects. As a one-paramter set, they have "leaf" projections ( for each parameter value.  As geometric objects they act as the infinite union of all their "leaf" (cross sections for each parameter value).

According to the Feature Model, geometry is a property of a Feature. Since we have defined MF_OneParamGeometry, it stands to reason that there can be a MF_OneParamProperty. Likewise, there can be a subclass MF_TemporalProperty. 

Therefore, MF_TemporalProperty can represent any Feature Property which changes with time. The JSON encoding standard for Moving Features provides us whith this capability.

==== TemporalProperties Object

A TemporalProperties object is a JSON array of ParametricValues objects that groups a collection of dynamic non-spatial attributes and its parametric values with time.

===== ParametricValues Object

A ParametricValues object is a JSON object that represents a collection of parametric values of dynamic non-spatial attributes that are ascertained at the same times. A parametric value may be a time-varying measure, a sequence of texts, or a sequence of images. Even though the parametric value may depend on the spatiotemporal location, MF-JSON Prism only considers the temporal dependencies of their changes of value.